DROP DATABASE IF EXISTS kc;
CREATE DATABASE IF NOT EXISTS kc;
USE kc;

-- Table tp1 (TINYINT)
CREATE TABLE IF NOT EXISTS tp1(a TINYINT);

INSERT INTO tp1 VALUES (10);
INSERT INTO tp1 VALUES (125);
INSERT INTO tp1 VALUES (128);   
INSERT INTO tp1 VALUES (-128);
INSERT INTO tp1 VALUES (-130);  

DESC tp1;
SELECT * FROM tp1;


-- Table tp2 (TINYINT UNSIGNED)
CREATE TABLE IF NOT EXISTS tp2(a TINYINT UNSIGNED);

INSERT INTO tp2 VALUES (10);
INSERT INTO tp2 VALUES (125);
INSERT INTO tp2 VALUES (128);
INSERT INTO tp2 VALUES (250);
INSERT INTO tp2 VALUES (-130);  

DESC tp2;
SELECT * FROM tp2;