DROP DATABASE IF EXISTS kc;
CREATE DATABASE IF NOT EXISTS kc;
USE kc;

-- FLOAT
CREATE TABLE IF NOT EXISTS tp1(a FLOAT);
INSERT INTO tp1 VALUES (20/3);
SELECT * FROM tp1;


-- DOUBLE
CREATE TABLE IF NOT EXISTS tp2(a DOUBLE);
INSERT INTO tp2 VALUES (20/3);
SELECT * FROM tp2;


-- DECIMAL (high precision)
CREATE TABLE IF NOT EXISTS tp3(a DECIMAL(30,12));
INSERT INTO tp3 VALUES (20/3);
SELECT * FROM tp3;